# NEXT Transformer — Cached EnergyBench Run

This notebook trains the NEXT Transformer from a validated disk-backed token cache while keeping the shared EnergyBench training and evaluation functions unchanged. Build and benchmark the cache with the standalone scripts before running this notebook.

## 1. Paths and imports

The workflow copy owns splitting, training, checkpoints, metrics, evaluation, and plotting. The NEXT package owns tokenization, cache loading, positional encoding, and the Transformer model.

In [1]:
from pathlib import Path
import hashlib
import json
import sys
import time

import pandas as pd
import torch

PROJECT_ROOT = Path(
    "/home/klz/Data/zeronu_benchmark/Transformer_Approach"
)
NEXT_ROOT = PROJECT_ROOT / "next_detector"
WORKFLOW_ROOT = PROJECT_ROOT / "evalutaions_workflow"

for path in (WORKFLOW_ROOT, NEXT_ROOT):
    path_text = str(path)
    if path_text not in sys.path:
        sys.path.insert(0, path_text)

from simple_energybench import (
    EvaluationConfig,
    TrainingConfig,
    evaluate_classification,
    set_seed,
    train_model,
)
from next_transformer import (
    NEXTTransformerClassifier,
    TokenizationConfig,
    find_token_cache,
    prepare_cached_dataset,
    validate_token_cache,
)

import simple_energybench
import next_transformer

print("EnergyBench:", simple_energybench.__file__)
print("Transformer:", next_transformer.__file__)

EnergyBench: /home/klz/Data/zeronu_benchmark/Transformer_Approach/evalutaions_workflow/simple_energybench/__init__.py
Transformer: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/next_transformer/__init__.py

## 2. Official configuration

Only `num_workers` is changed from the collaboration defaults. It is a data-loading throughput setting; model optimization and evaluation settings remain standard.

In [2]:
DATA_ROOT = Path(
    "/home/klz/Data/zeronu_benchmark/NEXT"
)
OUTPUT_ROOT = NEXT_ROOT / "results"
MANIFEST_PATH = OUTPUT_ROOT / "event_split.json"
CACHE_ROOT = NEXT_ROOT / "token_cache"
FINAL_OUTPUT_ROOT = OUTPUT_ROOT / "final_cached_v1"
FINAL_OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

training_config = TrainingConfig(num_workers=8)
evaluation_config = EvaluationConfig()
set_seed(training_config.seed, training_config.deterministic)

print(training_config)
print(evaluation_config)
print("Dataset:", DATA_ROOT)
print("Split manifest:", MANIFEST_PATH)
print("Cache root:", CACHE_ROOT)
print("Outputs:", FINAL_OUTPUT_ROOT)

TrainingConfig(batch_size=64, epochs=50, learning_rate=0.0005, weight_decay=0.0001, gradient_clip_norm=1.0, early_stopping_patience=5, early_stopping_min_delta=0.0, seed=42, deterministic=False, use_amp=True, amp_precision='auto', optimizer='adamw', scheduler='cosine', classification_loss='bce_with_logits', regression_loss='mse', device='auto', num_workers=8)
EvaluationConfig(energy_bin_width_kev=5.0, energy_grid_min_kev=0.0, energy_grid_max_kev=3000.0, energy_grid_bin_count=600, energy_unit='MeV', matching_target='overlap', min_per_class=20, min_valid_bins=2, support_trim_quantile=0.005, energy_roi=None, min_coverage=0.5, target_tpr=0.9, score_bins=20, min_per_bin=20, distance_correlation_max_samples=1200, performance_bins=10, fractional_energy_floor=None, seed=42)
Dataset: /home/klz/Data/zeronu_benchmark/NEXT
Split manifest: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/results/event_split.json
Cache root: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/token_cache
Outputs: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/results/final_cached_v1

## 3. Experiments and deadline gate

All four ablations run sequentially. Each tokenization cache is loaded once and reused by both positional encodings. A model is marked complete only after training and held-out test evaluation are written to the summary CSV. Re-running the notebook skips completed models.

In [3]:
ALL_EXPERIMENTS = [
    {
        "model_id": "transformer_001_sampled_hits_coordinate_mlp",
        "tokenization": "sampled_hits",
        "position_encoding": "coordinate_mlp",
    },
    {
        "model_id": "transformer_002_voxel_coordinate_mlp",
        "tokenization": "voxel",
        "position_encoding": "coordinate_mlp",
    },
    {
        "model_id": "transformer_003_voxel_fourier_xyz",
        "tokenization": "voxel",
        "position_encoding": "fourier_xyz",
    },
    {
        "model_id": "transformer_004_sampled_hits_fourier_xyz",
        "tokenization": "sampled_hits",
        "position_encoding": "fourier_xyz",
    },
]

# Run the complete 2-tokenization x 2-position-encoding benchmark.
RUN_MODEL_IDS = {
    "transformer_001_sampled_hits_coordinate_mlp",
    "transformer_002_voxel_coordinate_mlp",
    "transformer_003_voxel_fourier_xyz",
    "transformer_004_sampled_hits_fourier_xyz",
}

EXPERIMENTS = [
    experiment
    for experiment in ALL_EXPERIMENTS
    if experiment["model_id"] in RUN_MODEL_IDS
]

print("Selected experiments:")
for experiment in EXPERIMENTS:
    print(" -", experiment["model_id"])

Selected experiments:
 - transformer_001_sampled_hits_coordinate_mlp
 - transformer_002_voxel_coordinate_mlp
 - transformer_003_voxel_fourier_xyz
 - transformer_004_sampled_hits_fourier_xyz

## 4. Resolve and validate required caches

A cache is accepted only when its split hash, tokenizer configuration, tokenizer-source hash, shapes, dtypes, and `_SUCCESS` marker all validate.

In [4]:
tokenization_configs = {
    "voxel": TokenizationConfig(
        tokenization="voxel",
        max_tokens=512,
        voxel_size=15.0,
        coordinate_scale=1000.0,
        center_coordinates=True,
        voxel_truncation="occupancy",
        seed=training_config.seed,
    ),
    "sampled_hits": TokenizationConfig(
        tokenization="sampled_hits",
        max_tokens=512,
        voxel_size=15.0,
        coordinate_scale=1000.0,
        center_coordinates=True,
        voxel_truncation="occupancy",
        seed=training_config.seed,
    ),
}

required_tokenizations = {
    experiment["tokenization"]
    for experiment in EXPERIMENTS
}

data_by_tokenization = {}
cache_reports = {}
loader_optimizations = {}

for tokenization_name in sorted(required_tokenizations):
    config = tokenization_configs[tokenization_name]
    trim_padding = tokenization_name == "voxel"
    compact_training_batches = True
    cache_dir = find_token_cache(
        CACHE_ROOT,
        DATA_ROOT,
        MANIFEST_PATH,
        config,
    )
    report = validate_token_cache(
        cache_dir,
        DATA_ROOT,
        MANIFEST_PATH,
        config,
    )
    prepared = prepare_cached_dataset(
        cache_dir,
        batch_size=training_config.batch_size,
        num_workers=training_config.num_workers,
        seed=training_config.seed,
        pin_memory=torch.cuda.is_available(),
        trim_padding=trim_padding,
        compact_training_batches=compact_training_batches,
    )
    data_by_tokenization[tokenization_name] = prepared
    cache_reports[tokenization_name] = report
    loader_optimizations[tokenization_name] = {
        "trim_padding": trim_padding,
        "compact_training_batches": compact_training_batches,
    }
    print()
    print(tokenization_name, "cache:", cache_dir)
    print("counts:", prepared.counts)
    print("loader optimizations:", loader_optimizations[tokenization_name])

sampled_hits cache: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/token_cache/sampled_hits_b4460785f223_4ba5d22f5536
counts: {'boundary_files': ['0nubb_part_4/ATPC_0nubb_5bar_Efilt_5.0percent_smear_3983.h5', '0nubb_part_5/ATPC_0nubb_5bar_Efilt_5.0percent_smear_5204.h5', 'Bi_part_6/ATPC_Bi_ion_5bar_Efilt_5.0percent_smear_3505.h5', 'Bi_part_7/ATPC_Bi_ion_5bar_Efilt_5.0percent_smear_3894.h5'], 'by_class': {'0nubb': {'test': 64879, 'total': 648793, 'train': 519034, 'validation': 64880}, 'Bi214': {'test': 51670, 'total': 516696, 'train': 413357, 'validation': 51669}}, 'fractions': {'test': 0.10000008580089559, 'train': 0.7999998283982088, 'validation': 0.10000008580089559}, 'test': 116549, 'total': 1165489, 'train': 932391, 'validation': 116549}
loader optimizations: {'trim_padding': False, 'compact_training_batches': True}

voxel cache: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/token_cache/voxel_b4460785f223_ae165e692ff1
counts: {'boundary_files': ['0nubb_part_4/ATPC_0nubb_5bar_Efilt_5.0percent_smear_3983.h5', '0nubb_part_5/ATPC_0nubb_5bar_Efilt_5.0percent_smear_5204.h5', 'Bi_part_6/ATPC_Bi_ion_5bar_Efilt_5.0percent_smear_3505.h5', 'Bi_part_7/ATPC_Bi_ion_5bar_Efilt_5.0percent_smear_3894.h5'], 'by_class': {'0nubb': {'test': 64879, 'total': 648793, 'train': 519034, 'validation': 64880}, 'Bi214': {'test': 51670, 'total': 516696, 'train': 413357, 'validation': 51669}}, 'fractions': {'test': 0.10000008580089559, 'train': 0.7999998283982088, 'validation': 0.10000008580089559}, 'test': 116549, 'total': 1165489, 'train': 932391, 'validation': 116549}
loader optimizations: {'trim_padding': True, 'compact_training_batches': True}

## 5. Official preflight

These assertions stop the run before training if the cache, split, standard training configuration, or CUDA environment is wrong.

In [5]:
EXPECTED_COUNTS = {
    "total": 1_165_489,
    "train": 932_391,
    "validation": 116_549,
    "test": 116_549,
}

for tokenization_name, prepared in data_by_tokenization.items():
    for name, expected in EXPECTED_COUNTS.items():
        assert prepared.counts[name] == expected, (
            tokenization_name,
            name,
            prepared.counts[name],
            expected,
        )
    assert prepared.manifest_path.resolve() == MANIFEST_PATH.resolve()
    assert prepared.cache_manifest_path.is_file()

assert training_config.epochs == 50
assert training_config.batch_size == 64
assert training_config.learning_rate == 5e-4
assert training_config.early_stopping_patience == 5
assert training_config.num_workers == 8
assert torch.cuda.is_available()
assert loader_optimizations["voxel"] == {
    "trim_padding": True,
    "compact_training_batches": True,
}
assert loader_optimizations["sampled_hits"] == {
    "trim_padding": False,
    "compact_training_batches": True,
}

print("Official cached-run preflight passed.")
print("GPU:", torch.cuda.get_device_name(0))
print("Selected models:", len(EXPERIMENTS))

Official cached-run preflight passed.
GPU: NVIDIA GeForce RTX 5090
Selected models: 4

## 6. Train and evaluate

EnergyBench saves `best_model.pt` and `last_model.pt` while training. When early stopping or epoch 50 is reached, `train_model` restores the best-validation-AUC weights in memory, and `evaluate_classification` evaluates those weights once on the held-out test split.

In [6]:
SUMMARY_PATH = FINAL_OUTPUT_ROOT / "transformer_results.csv"

if SUMMARY_PATH.is_file():
    existing_results = pd.read_csv(SUMMARY_PATH)
    experiment_rows = existing_results.to_dict(orient="records")
    completed_model_ids = set(existing_results["model_id"].astype(str))
    print("Previously completed:", sorted(completed_model_ids))
else:
    experiment_rows = []
    completed_model_ids = set()

for experiment in EXPERIMENTS:
    model_id = experiment["model_id"]
    if model_id in completed_model_ids:
        print("Skipping completed model:", model_id)
        continue

    tokenization_name = experiment["tokenization"]
    position_encoding = experiment["position_encoding"]
    prepared_data = data_by_tokenization[tokenization_name]
    representation_config = tokenization_configs[tokenization_name]
    cache_report = cache_reports[tokenization_name]
    run_root = FINAL_OUTPUT_ROOT / model_id

    print()
    print("=" * 80)
    print(model_id)
    print("Tokenization:", tokenization_name)
    print("Position encoding:", position_encoding)
    print("Cache:", cache_report["cache_dir"])
    print("Output:", run_root)
    print("=" * 80)

    set_seed(training_config.seed, training_config.deterministic)
    model = NEXTTransformerClassifier(
        position_encoding=position_encoding,
        feature_dim=2,
        d_model=64,
        nhead=4,
        num_layers=2,
        dim_feedforward=256,
        dropout=0.1,
        num_frequencies=6,
    )
    parameter_count = sum(
        parameter.numel()
        for parameter in model.parameters()
        if parameter.requires_grad
    )
    print("Trainable parameters:", f"{parameter_count:,}")

    representation_path = run_root / "representation_config.json"
    representation_path.parent.mkdir(parents=True, exist_ok=True)
    representation_record = {
        **representation_config.to_dict(),
        "position_encoding": position_encoding,
        "feature_dim": 2,
        "d_model": 64,
        "nhead": 4,
        "num_layers": 2,
        "dim_feedforward": 256,
        "dropout": 0.1,
        "num_frequencies": 6,
        "parameter_count": parameter_count,
        "trim_padding": loader_optimizations[tokenization_name][
            "trim_padding"
        ],
        "compact_training_batches": loader_optimizations[
            tokenization_name
        ]["compact_training_batches"],
        "manifest_path": str(prepared_data.manifest_path),
        "cache_manifest_path": str(prepared_data.cache_manifest_path),
        "source_manifest_sha256": cache_report["source_manifest_sha256"],
        "tokenization_config_sha256": cache_report[
            "tokenization_config_sha256"
        ],
        "tokenization_source_sha256": cache_report[
            "tokenization_source_sha256"
        ],
    }
    representation_path.write_text(
        json.dumps(representation_record, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    training_start = time.perf_counter()
    history = train_model(
        model,
        prepared_data.train_loader,
        prepared_data.validation_loader,
        config=training_config,
        task="classification",
        output_dir=run_root / "training",
        overwrite=False,
    )
    training_seconds = time.perf_counter() - training_start

    print("Best epoch:", history["best_epoch"])
    print("Best validation AUC:", history["best_metric"])

    evaluation_start = time.perf_counter()
    results = evaluate_classification(
        model,
        prepared_data.test_loader,
        device=training_config.device,
        output_dir=run_root / "evaluation",
        config=evaluation_config,
        overwrite=False,
    )
    evaluation_seconds = time.perf_counter() - evaluation_start

    row = {
        "model_id": model_id,
        "tokenization": tokenization_name,
        "position_encoding": position_encoding,
        "parameter_count": parameter_count,
        "best_epoch": history["best_epoch"],
        "best_validation_auc": history["best_metric"],
        "test_events": results["n_events"],
        "inclusive_auc": results["auc"],
        "energy_matched_auc": results["matched_auc"],
        "matched_auc_status": results["matched_auc_status"],
        "common_support_auc": results["common_support_auc"],
        "shortcut_gap": results["shortcut_gap"],
        "energy_independence_score": results["energy_independence_score"],
        "worst_energy_independence_score": results[
            "worst_energy_independence_score"
        ],
        "training_seconds": training_seconds,
        "evaluation_seconds": evaluation_seconds,
        "cache_manifest_path": str(prepared_data.cache_manifest_path),
        "cache_config_sha256": cache_report["tokenization_config_sha256"],
    }
    experiment_rows.append(row)
    pd.DataFrame(experiment_rows).to_csv(SUMMARY_PATH, index=False)
    display(pd.DataFrame([row]))

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

Previously completed: ['transformer_001_sampled_hits_coordinate_mlp']
Skipping completed model: transformer_001_sampled_hits_coordinate_mlp

================================================================================
transformer_002_voxel_coordinate_mlp
Tokenization: voxel
Position encoding: coordinate_mlp
Cache: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/token_cache/voxel_b4460785f223_ae165e692ff1
Output: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/results/final_cached_v1/transformer_002_voxel_coordinate_mlp
================================================================================
Trainable parameters: 111,105

Epoch 001/050 | train loss 0.443215 | val loss 0.975452 | val auc 0.899707

Epoch 002/050 | train loss 0.368593 | val loss 0.299794 | val auc 0.944521

Epoch 003/050 | train loss 0.324155 | val loss 0.278406 | val auc 0.958665

Epoch 004/050 | train loss 0.284102 | val loss 0.45635 | val auc 0.958191

Epoch 005/050 | train loss 0.25755 | val loss 0.244094 | val auc 0.966702

Epoch 006/050 | train loss 0.239198 | val loss 0.208379 | val auc 0.972121

Epoch 007/050 | train loss 0.227931 | val loss 0.219551 | val auc 0.972625

Epoch 008/050 | train loss 0.216156 | val loss 0.281516 | val auc 0.973516

Epoch 009/050 | train loss 0.204969 | val loss 0.188392 | val auc 0.976464

Epoch 010/050 | train loss 0.197329 | val loss 0.257665 | val auc 0.975856

Epoch 011/050 | train loss 0.193104 | val loss 0.181136 | val auc 0.978258

Epoch 012/050 | train loss 0.186376 | val loss 0.175142 | val auc 0.979859

Epoch 013/050 | train loss 0.183019 | val loss 0.171156 | val auc 0.980496

Epoch 014/050 | train loss 0.178827 | val loss 0.179157 | val auc 0.981021

Epoch 015/050 | train loss 0.174455 | val loss 0.165851 | val auc 0.981885

Epoch 016/050 | train loss 0.170806 | val loss 0.181502 | val auc 0.981681

Epoch 017/050 | train loss 0.169016 | val loss 0.170188 | val auc 0.981916

Epoch 018/050 | train loss 0.165452 | val loss 0.199019 | val auc 0.983393

Epoch 019/050 | train loss 0.165371 | val loss 0.192914 | val auc 0.982893

Epoch 020/050 | train loss 0.160832 | val loss 0.174813 | val auc 0.983394

Epoch 021/050 | train loss 0.157917 | val loss 0.20005 | val auc 0.982754

Epoch 022/050 | train loss 0.156465 | val loss 0.187654 | val auc 0.983885

Epoch 023/050 | train loss 0.154614 | val loss 0.153406 | val auc 0.984766

Epoch 024/050 | train loss 0.152292 | val loss 0.14451 | val auc 0.985598

Epoch 025/050 | train loss 0.150664 | val loss 0.149261 | val auc 0.985418

Epoch 026/050 | train loss 0.149453 | val loss 0.161856 | val auc 0.986061

Epoch 027/050 | train loss 0.147995 | val loss 0.144859 | val auc 0.985847

Epoch 028/050 | train loss 0.145878 | val loss 0.194038 | val auc 0.984702

Epoch 029/050 | train loss 0.14451 | val loss 0.144818 | val auc 0.986148

Epoch 030/050 | train loss 0.142959 | val loss 0.145527 | val auc 0.986141

Epoch 031/050 | train loss 0.141312 | val loss 0.142536 | val auc 0.986302

Epoch 032/050 | train loss 0.139808 | val loss 0.144698 | val auc 0.986858

Epoch 033/050 | train loss 0.138905 | val loss 0.147691 | val auc 0.987061

Epoch 034/050 | train loss 0.137672 | val loss 0.138919 | val auc 0.986989

Epoch 035/050 | train loss 0.136934 | val loss 0.143384 | val auc 0.987511

Epoch 036/050 | train loss 0.136031 | val loss 0.153963 | val auc 0.987372

Epoch 037/050 | train loss 0.134327 | val loss 0.14141 | val auc 0.987719

Epoch 038/050 | train loss 0.134023 | val loss 0.137988 | val auc 0.98783

Epoch 039/050 | train loss 0.132993 | val loss 0.134896 | val auc 0.987588

Epoch 040/050 | train loss 0.132013 | val loss 0.153905 | val auc 0.987371

Epoch 041/050 | train loss 0.131751 | val loss 0.145223 | val auc 0.987905

Epoch 042/050 | train loss 0.130512 | val loss 0.147635 | val auc 0.987777

Epoch 043/050 | train loss 0.130292 | val loss 0.135698 | val auc 0.988112

Epoch 044/050 | train loss 0.129853 | val loss 0.147727 | val auc 0.987931

Epoch 045/050 | train loss 0.129119 | val loss 0.143314 | val auc 0.988093

Epoch 046/050 | train loss 0.129017 | val loss 0.14013 | val auc 0.988122

Epoch 047/050 | train loss 0.128242 | val loss 0.14298 | val auc 0.988214

Epoch 048/050 | train loss 0.128287 | val loss 0.141971 | val auc 0.988166

Epoch 049/050 | train loss 0.128177 | val loss 0.142617 | val auc 0.988196

Epoch 050/050 | train loss 0.128296 | val loss 0.142653 | val auc 0.988179

Best epoch: 47
Best validation AUC: 0.9882135888505318

,model_id,tokenization,position_encoding,parameter_count,best_epoch,best_validation_auc,test_events,inclusive_auc,energy_matched_auc,matched_auc_status,common_support_auc,shortcut_gap,energy_independence_score,worst_energy_independence_score,training_seconds,evaluation_seconds,cache_manifest_path,cache_config_sha256
0,transformer_002_voxel_coordinate_mlp,voxel,coordinate_mlp,111105,47,0.988214,116549,0.987943,0.987718,ok,0.987933,0.000214,0.973246,0.966642,22388.583095,22.976107,/home/klz/Data/zeronu_benchmark/Transformer_Ap...,ae165e692ff169963dcfa8816ba8df26fa06140045cfe3...

================================================================================
transformer_003_voxel_fourier_xyz
Tokenization: voxel
Position encoding: fourier_xyz
Cache: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/token_cache/voxel_b4460785f223_ae165e692ff1
Output: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/results/final_cached_v1/transformer_003_voxel_fourier_xyz
================================================================================
Trainable parameters: 113,409

Epoch 001/050 | train loss 0.387033 | val loss 0.705318 | val auc 0.922986

Epoch 002/050 | train loss 0.324466 | val loss 0.286275 | val auc 0.947946

Epoch 003/050 | train loss 0.302952 | val loss 0.274916 | val auc 0.954135

Epoch 004/050 | train loss 0.279779 | val loss 0.339846 | val auc 0.957509

Epoch 005/050 | train loss 0.267039 | val loss 0.262684 | val auc 0.961618

Epoch 006/050 | train loss 0.254375 | val loss 0.236738 | val auc 0.963994

Epoch 007/050 | train loss 0.245668 | val loss 0.238506 | val auc 0.966068

Epoch 008/050 | train loss 0.235538 | val loss 0.32852 | val auc 0.965775

Epoch 009/050 | train loss 0.229465 | val loss 0.224711 | val auc 0.967377

Epoch 010/050 | train loss 0.224856 | val loss 0.292286 | val auc 0.967405

Epoch 011/050 | train loss 0.220435 | val loss 0.217937 | val auc 0.970098

Epoch 012/050 | train loss 0.217091 | val loss 0.210099 | val auc 0.970926

Epoch 013/050 | train loss 0.213533 | val loss 0.206457 | val auc 0.972733

Epoch 014/050 | train loss 0.209372 | val loss 0.207463 | val auc 0.97254

Epoch 015/050 | train loss 0.206714 | val loss 0.204168 | val auc 0.973087

Epoch 016/050 | train loss 0.203679 | val loss 0.208968 | val auc 0.973432

Epoch 017/050 | train loss 0.201214 | val loss 0.210998 | val auc 0.973761

Epoch 018/050 | train loss 0.198956 | val loss 0.207821 | val auc 0.975027

Epoch 019/050 | train loss 0.198022 | val loss 0.211172 | val auc 0.974882

Epoch 020/050 | train loss 0.194009 | val loss 0.20525 | val auc 0.974874

Epoch 021/050 | train loss 0.191524 | val loss 0.222695 | val auc 0.975764

Epoch 022/050 | train loss 0.189993 | val loss 0.215488 | val auc 0.975939

Epoch 023/050 | train loss 0.188059 | val loss 0.187534 | val auc 0.976486

Epoch 024/050 | train loss 0.186253 | val loss 0.192537 | val auc 0.976289

Epoch 025/050 | train loss 0.184194 | val loss 0.187442 | val auc 0.976964

Epoch 026/050 | train loss 0.183401 | val loss 0.202492 | val auc 0.976929

Epoch 027/050 | train loss 0.181105 | val loss 0.185887 | val auc 0.977231

Epoch 028/050 | train loss 0.179259 | val loss 0.216387 | val auc 0.977509

Epoch 029/050 | train loss 0.178181 | val loss 0.193966 | val auc 0.976732

Epoch 030/050 | train loss 0.176282 | val loss 0.189557 | val auc 0.977781

Epoch 031/050 | train loss 0.175239 | val loss 0.185688 | val auc 0.97769

Epoch 032/050 | train loss 0.173325 | val loss 0.188366 | val auc 0.978125

Epoch 033/050 | train loss 0.172711 | val loss 0.18986 | val auc 0.977808

Epoch 034/050 | train loss 0.171956 | val loss 0.182301 | val auc 0.978298

Epoch 035/050 | train loss 0.1705 | val loss 0.18358 | val auc 0.97861

Epoch 036/050 | train loss 0.169113 | val loss 0.191517 | val auc 0.978858

Epoch 037/050 | train loss 0.168092 | val loss 0.184038 | val auc 0.97845

Epoch 038/050 | train loss 0.167383 | val loss 0.178793 | val auc 0.97908

Epoch 039/050 | train loss 0.166674 | val loss 0.178543 | val auc 0.978703

Epoch 040/050 | train loss 0.165273 | val loss 0.192192 | val auc 0.978966

Epoch 041/050 | train loss 0.164696 | val loss 0.187179 | val auc 0.979168

Epoch 042/050 | train loss 0.163842 | val loss 0.188655 | val auc 0.979215

Epoch 043/050 | train loss 0.163692 | val loss 0.181104 | val auc 0.978892

Epoch 044/050 | train loss 0.162366 | val loss 0.189399 | val auc 0.979133

Epoch 045/050 | train loss 0.162007 | val loss 0.186764 | val auc 0.97882

Epoch 046/050 | train loss 0.161482 | val loss 0.182848 | val auc 0.979084

Epoch 047/050 | train loss 0.161019 | val loss 0.186895 | val auc 0.979251

Epoch 048/050 | train loss 0.161002 | val loss 0.186092 | val auc 0.979226

Epoch 049/050 | train loss 0.160695 | val loss 0.18667 | val auc 0.979264

Epoch 050/050 | train loss 0.161077 | val loss 0.186551 | val auc 0.979266

Best epoch: 50
Best validation AUC: 0.9792661922224792

,model_id,tokenization,position_encoding,parameter_count,best_epoch,best_validation_auc,test_events,inclusive_auc,energy_matched_auc,matched_auc_status,common_support_auc,shortcut_gap,energy_independence_score,worst_energy_independence_score,training_seconds,evaluation_seconds,cache_manifest_path,cache_config_sha256
0,transformer_003_voxel_fourier_xyz,voxel,fourier_xyz,113409,50,0.979266,116549,0.978971,0.978698,ok,0.978933,0.000236,0.972763,0.967611,31440.345512,54.083545,/home/klz/Data/zeronu_benchmark/Transformer_Ap...,ae165e692ff169963dcfa8816ba8df26fa06140045cfe3...

================================================================================
transformer_004_sampled_hits_fourier_xyz
Tokenization: sampled_hits
Position encoding: fourier_xyz
Cache: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/token_cache/sampled_hits_b4460785f223_4ba5d22f5536
Output: /home/klz/Data/zeronu_benchmark/Transformer_Approach/next_detector/results/final_cached_v1/transformer_004_sampled_hits_fourier_xyz
================================================================================
Trainable parameters: 113,409

Epoch 001/050 | train loss 0.394378 | val loss 0.566489 | val auc 0.916457

Epoch 002/050 | train loss 0.352448 | val loss 0.339458 | val auc 0.927332

Epoch 003/050 | train loss 0.341299 | val loss 0.338749 | val auc 0.931173

Epoch 004/050 | train loss 0.331739 | val loss 0.355966 | val auc 0.932492

Epoch 005/050 | train loss 0.324572 | val loss 0.319675 | val auc 0.937005

Epoch 006/050 | train loss 0.318287 | val loss 0.312083 | val auc 0.939471

Epoch 007/050 | train loss 0.314125 | val loss 0.324645 | val auc 0.93799

Epoch 008/050 | train loss 0.31052 | val loss 0.374448 | val auc 0.939441

Epoch 009/050 | train loss 0.306731 | val loss 0.305027 | val auc 0.941948

Epoch 010/050 | train loss 0.303585 | val loss 0.336187 | val auc 0.941365

Epoch 011/050 | train loss 0.301106 | val loss 0.304444 | val auc 0.942576

Epoch 012/050 | train loss 0.297998 | val loss 0.296195 | val auc 0.946111

Epoch 013/050 | train loss 0.296541 | val loss 0.29865 | val auc 0.948111

Epoch 014/050 | train loss 0.294891 | val loss 0.291886 | val auc 0.949694

Epoch 015/050 | train loss 0.299999 | val loss 0.285132 | val auc 0.950977

Epoch 016/050 | train loss 0.298103 | val loss 0.298997 | val auc 0.952896

Epoch 017/050 | train loss 0.291577 | val loss 0.310971 | val auc 0.949435

Epoch 018/050 | train loss 0.29156 | val loss 0.358864 | val auc 0.954252

Epoch 019/050 | train loss 0.292918 | val loss 0.328603 | val auc 0.954229

Epoch 020/050 | train loss 0.287928 | val loss 0.380444 | val auc 0.952469

Epoch 021/050 | train loss 0.283713 | val loss 0.510108 | val auc 0.94809

Epoch 022/050 | train loss 0.280237 | val loss 0.31511 | val auc 0.956246

Epoch 023/050 | train loss 0.276838 | val loss 0.25973 | val auc 0.957875

Epoch 024/050 | train loss 0.272654 | val loss 0.261108 | val auc 0.956865

Epoch 025/050 | train loss 0.270059 | val loss 0.255547 | val auc 0.958353

Epoch 026/050 | train loss 0.273433 | val loss 0.285552 | val auc 0.958502

Epoch 027/050 | train loss 0.257855 | val loss 0.257545 | val auc 0.958928

Epoch 028/050 | train loss 0.27188 | val loss 0.33714 | val auc 0.958663

Epoch 029/050 | train loss 0.262351 | val loss 0.271751 | val auc 0.958941

Epoch 030/050 | train loss 0.261268 | val loss 0.28175 | val auc 0.958545

Epoch 031/050 | train loss 0.25266 | val loss 0.274463 | val auc 0.958187

Epoch 032/050 | train loss 0.248623 | val loss 0.262823 | val auc 0.960486

Epoch 033/050 | train loss 0.251496 | val loss 0.294598 | val auc 0.960159

Epoch 034/050 | train loss 0.248597 | val loss 0.248136 | val auc 0.961126

Epoch 035/050 | train loss 0.250405 | val loss 0.270516 | val auc 0.960798

Epoch 036/050 | train loss 0.238668 | val loss 0.283943 | val auc 0.960819

Epoch 037/050 | train loss 0.243425 | val loss 0.324255 | val auc 0.960565

Epoch 038/050 | train loss 0.24476 | val loss 0.250061 | val auc 0.961282

Epoch 039/050 | train loss 0.243455 | val loss 0.248606 | val auc 0.961666

Epoch 040/050 | train loss 0.236146 | val loss 0.272501 | val auc 0.961469

Epoch 041/050 | train loss 0.233566 | val loss 0.255591 | val auc 0.961923

Epoch 042/050 | train loss 0.233607 | val loss 0.26157 | val auc 0.961848

Epoch 043/050 | train loss 0.233997 | val loss 0.250302 | val auc 0.96185

Epoch 044/050 | train loss 0.229428 | val loss 0.268515 | val auc 0.962205

Epoch 045/050 | train loss 0.228672 | val loss 0.261904 | val auc 0.961916

Epoch 046/050 | train loss 0.228475 | val loss 0.256469 | val auc 0.961909

Epoch 047/050 | train loss 0.226832 | val loss 0.26682 | val auc 0.962019

Epoch 048/050 | train loss 0.227139 | val loss 0.260405 | val auc 0.962081

Epoch 049/050 | train loss 0.225562 | val loss 0.263864 | val auc 0.962062
Early stopping; restoring best model from epoch 44.
Best epoch: 44
Best validation AUC: 0.9622048362288272

,model_id,tokenization,position_encoding,parameter_count,best_epoch,best_validation_auc,test_events,inclusive_auc,energy_matched_auc,matched_auc_status,common_support_auc,shortcut_gap,energy_independence_score,worst_energy_independence_score,training_seconds,evaluation_seconds,cache_manifest_path,cache_config_sha256
0,transformer_004_sampled_hits_fourier_xyz,sampled_hits,fourier_xyz,113409,44,0.962205,116549,0.962684,0.96273,ok,0.962672,-0.000058,0.974274,0.973252,33656.279749,24.190334,/home/klz/Data/zeronu_benchmark/Transformer_Ap...,4ba5d22f5536d1812605f13cb4d23c329a24cdcba386e9...

## 7. Results saved so far

In [7]:
if SUMMARY_PATH.is_file():
    results_dataframe = pd.read_csv(SUMMARY_PATH)
    display(
        results_dataframe.sort_values(
            "energy_matched_auc",
            ascending=False,
        ).reset_index(drop=True)
    )
else:
    print("No complete cached experiment has been evaluated yet.")

,model_id,tokenization,position_encoding,parameter_count,best_epoch,best_validation_auc,test_events,inclusive_auc,energy_matched_auc,matched_auc_status,common_support_auc,shortcut_gap,energy_independence_score,worst_energy_independence_score,training_seconds,evaluation_seconds,cache_manifest_path,cache_config_sha256
0,transformer_002_voxel_coordinate_mlp,voxel,coordinate_mlp,111105,47,0.988214,116549,0.987943,0.987718,ok,0.987933,0.000214,0.973246,0.966642,22388.583095,22.976107,/home/klz/Data/zeronu_benchmark/Transformer_Ap...,ae165e692ff169963dcfa8816ba8df26fa06140045cfe3...
1,transformer_003_voxel_fourier_xyz,voxel,fourier_xyz,113409,50,0.979266,116549,0.978971,0.978698,ok,0.978933,0.000236,0.972763,0.967611,31440.345512,54.083545,/home/klz/Data/zeronu_benchmark/Transformer_Ap...,ae165e692ff169963dcfa8816ba8df26fa06140045cfe3...
2,transformer_001_sampled_hits_coordinate_mlp,sampled_hits,coordinate_mlp,111105,23,0.975839,116549,0.975567,0.975494,ok,0.975581,0.000087,0.975270,0.971484,14092.667939,32.013669,/home/klz/Data/zeronu_benchmark/Transformer_Ap...,4ba5d22f5536d1812605f13cb4d23c329a24cdcba386e9...
3,transformer_004_sampled_hits_fourier_xyz,sampled_hits,fourier_xyz,113409,44,0.962205,116549,0.962684,0.962730,ok,0.962672,-0.000058,0.974274,0.973252,33656.279749,24.190334,/home/klz/Data/zeronu_benchmark/Transformer_Ap...,4ba5d22f5536d1812605f13cb4d23c329a24cdcba386e9...